### ISSUE TITLE
Fix product_url in breadcrumb Schema.org structured data

### ISSUE THREAD

**Issue by meowsus** [workarea-commerce/workarea#83]
@sperks38 reported a bug around `product_urls` in the breadcrumb structured data. Triage and fix.

**Comment by meowsus** [comment]
@sperks38 it looks like #107 is also going to fix this issue. Please let me know if I've missed something in that PR!

**Comment by sperks38** [comment]
It doesn't. This issue is specific to `@product.breadcrumbs`. It builds a breadcrumb, but the last item (the product URL itself) is the root.

Example:
`{"@context":"http://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"@id":"http://localhost:3000/","name":"Home"}},{"@type":"ListItem","position":2,"item":{"@id":"http://localhost:3000/pages/clothing","name":"Clothing"}},{"@type":"ListItem","position":3,"item":{"@id":"http://localhost:3000/categories/t-shirts","name":"T-Shirts"}},{"@type":"ListItem","position":4,"item":{"@id":"http://localhost:3000/","name":"Ergonomic Steel Hat"}}]}`

**Comment by sperks38** [comment]
To be more specific, this is on product pages.

**Comment by meowsus** [comment]
Ah! Okay, thanks for this. #107 will no longer close this issue and I'll look into it ASAP.

**Comment by meowsus** [comment]
@tubbo if you go to a product page and view the source, searching for "BreadcrumbList", you'll see the code @sperks38 references in his comment. 

It looks as if the `last` breadcrumb, for products at least, is not generating the proper URL. We have logic around setting the `name` properly for these breadcrumbs, but the URL isn't being generated properly.
