### ISSUE TITLE
Look into /login and /current_user.json XHR logs in storefront system tests

### ISSUE THREAD

**Issue by ebigler** [workarea-commerce/workarea#90]

**Comment by ebigler** [comment]
understand and fix why the XHR requests are being made while browsing

**Comment by tubbo** [comment]
These errors are being printed to console in `Storefront::LoginSystemTest#test_user_lock_outs` and `Storefront::PasswordsSystemTest#test_admin_resetting_a_password`.

The lock-outs test is basically trying a bad password as many times as `Workarea.config.allowed_login_attempts` will allow before locking them out. This is what's causing the 422 responses, since `/login` renders the 422 status code when a login fails.

The admin reset password test is simulating what happens when an admin accesses the site, but their password has expired. In this case, `/current_user.json` is rendering a 401, because the `Authorization#require_password_changes` before_filter won't allow the request to succeed when the password needs to be changed.

I propose that we filter out these messages since they are expected to occur in the normal run of our tests, like so:

```ruby
Capybara::Chromedriver::Logger.filters = [
  /(login|current_user\.json) - Failed to load resource: the server responded with a status of (401|422)/
]
